const champs = [
    {
        id:'1',
        SeriesFinal:"(4 - 3)",
        FinalsMVP:"Bill Russell",
        Year:"1957",
        Celtics:' Boston Celtics',
        Opponent:'St Louis Hawks',
        CeltsScore:"125",
        OpponentScore:"123",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"https://upload.wikimedia.org/wikipedia/commons/5/5c/Celtics_1956-57.jpg",
    },
    {
        id:'2',
        SeriesFinal:"(4 - 0)",
        FinalsMVP:"Bill Russell",
        Year:"1959",
        Celtics:'Boston Celtics',
        Opponent:'Minneapolis Lakers',
        CeltsScore:"118",
        OpponentScore:"130",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
    {
        id:'3',
        SeriesFinal:"(4 - 3)",
        FinalsMVP:"Bill Russell",
        Year:"1960",
        Celtics:'Boston Celtics',
        Opponent:'St Louis Hawks',
        CeltsScore:"122",
        OpponentScore:"103",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
    {
        id:'4',
        SeriesFinal:"(4 -1)",
        FinalsMVP:"Bill Russell",
        Year:"1961",
        Celtics:'Boston Celtics',
        Opponent:'St Louis Hawks',
        CeltsScore:"121",
        OpponentScore:"112",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
     {
        id:'5',
        SeriesFinal:"(4 - 3)",
        FinalsMVP:"Bill Russell",
        Year:"1962",
        Celtics:'Boston Celtics',
        Opponent:'Minneapolis Lakers',
        CeltsScore:"110",
        OpponentScore:"107",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
      {
        id:'6',
        SeriesFinal:"(4 - 2)",
        FinalsMVP:"Bill Russell",
        Year:"1964",
        Celtics:'Boston Celtics',
        Opponent:'Minneapolis Lakers',
        CeltsScore:"112",
        OpponentScore:"109",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
    {
        id:'7',
        SeriesFinal:"(4 - 1)",
        FinalsMVP:"Bill Russell",
        Year:"1965",
        Celtics:'Boston Celtics',
        Opponent:'San Francisco Warriors',
        CeltsScore:"105",
        OpponentScore:"99",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
     {
        id:'8',
        SeriesFinal:"(4 - 1)",
        FinalsMVP:"Bill Russell",
        Year:"1965",
        Celtics:'Boston Celtics',
        Opponent:'Minneapolis Lakers',
        CeltsScore:"129",
        OpponentScore:"96",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
     {
        id:'9',
        SeriesFinal:"(4 - 3)",
        FinalsMVP:"Bill Russell",
        Year:"1966",
        Celtics:'Boston Celtics',
        Opponent:'Minneapolis Lakers',
        CeltsScore:"95",
        OpponentScore:"93",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
     {
        id:'10',
        SeriesFinal:"(4 - 2)",
        FinalsMVP:"Bill Russell",
        Year:"1968",
        Celtics:'Boston Celtics',
        Opponent:'Minneapolis Lakers',
        CeltsScore:"124",
        OpponentScore:"109",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
     {
        id:'11',
        SeriesFinal:"(4 - 3)",
        FinalsMVP:"Bill Russell",
        Year:"1969",
        Celtics:'Boston Celtics',
        Opponent:'Minneapolis Lakers',
        CeltsScore:"108",
        OpponentScore:"106",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
    {
        id:'12',
        SeriesFinal:"(4 - 3)",
        FinalsMVP:"Dave Cowens",
        Year:"1974",
        Celtics:'Boston Celtics',
        Opponent:'Milwaukee Bucks',
        CeltsScore:"102",
        OpponentScore:"87",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
    {
        id:'13',
        SeriesFinal:"(4 - 2)",
        FinalsMVP:"John Havlicek",
        Year:"1976",
        Celtics:'Boston Celtics',
        Opponent:'Phoenix Suns',
        CeltsScore:"87",
        OpponentScore:"80",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
    {
        id:'14',
        SeriesFinal:"(4 - 2)",
        FinalsMVP:"Larry Bird",
        Year:"1981",
        Celtics:'Boston Celtics',
        Opponent:'Houston Rockets',
        CeltsScore:"102",
        OpponentScore:"91",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
    {
        id:'15',
        SeriesFinal:"(4-3)",
        FinalsMVP:"Larry Bird",
        Year:"1984",
        Celtics:'Boston Celtics',
        Opponent:'Los Angeles Lakers',
        CeltsScore:"111",
        OpponentScore:"102",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
   {
        id:'16',
        SeriesFinal:"(4 - 2)",
        FinalsMVP:"Larry Bird",
        Year:"1986",
        Celtics:'Boston Celtics',
        Opponent:'Houston Rockets',
        CeltsScore:"114",
        OpponentScore:"97",
        CeltsLogo:"",
        OpponentLogo:"",
        Banner:"",
    },
];

module.exports = champs;