const CelticsRoster = [
    {
        id: '1',
        Name:'Jayson Tatum 0',
        Position:"Small Forward",
        Height:"6'8ft",
        Wieght:"210lbs",
        Image:'https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png',
    },
    {
        id: '2',
        Name:'Jalyn Brown 7',
        Position:"Shooting Guard",
        Height:"6'6ft",
        Wieght:"223lbs",
        Image:'',
    },
    {
        id: '3',
        Name:'Marcus Smart 36',
        Position:"Point Guard",
        Height:"6'4ft",
        Wieght:"220lbs",
        Image:'',
    },
    {
        id: '4',
        Name:'Robert Williams 44',
        Position:"Center",
        Height:"6'9ft",
        Wieght:"237lbs",
        Image:'',
    },
    {
        id: '5',
        Name:'Al Horford 42',
        Position:"Power Forward",
        Height:"6'9ft",
        Wieght:"240lbs",
        Image:'',
    },
    {
        id: '6',
        Name:'Derrick White 9',
        Position:"Shooting Guard",
        Height:"6'4ft",
        Wieght:"190lbs",
        Image:'',
    },
    {
        id: '7',
        Name:'Grant Williams 12',
        Position:"Power Forward",
        Height:"6'6ft",
        Wieght:"236lbs",
        Image:'',
    },
    {
        id: '8',
        Name:'Payton Pritchard 11',
        Position:"Point Guard",
        Height:"6'1ft",
        Wieght:"195lbs",
        Image:'',
    },
    {
        id: '9',
        Name:'Aaron Nesmith 26',
        Position:"Shooting Guard",
        Height:"6'5ft",
        Wieght:"215lbs",
        Image:'',
    },
    {
        id: '10',
        Name:'Daniel Theis 27',
        Position:"Center",
        Height:"6'9ft",
        Wieght:"245lbs",
        Image:'',
    },
    {
        id: '11',
        Name:'Sam Hauser 30',
        Position:"Small Forward",
        Height:"6'7ft",
        Wieght:"217lbs",
        Image:'',
    },
    {
        id: '12',
        Name:'Luke Kornet 40',
        Position:"Center",
        Height:"7'2ft",
        Wieght:"250lbs",
        Image:'',
    },
    {
        id: '13',
        Name:'Nik Stauskas 9',
        Position:"Shooting Guard",
        Height:"6'6ft",
        Wieght:"207lbs",
        Image:'',
    },
    {
        id: '14',
        Name:'Bodric Thomas 97',
        Position:"Shooting Guard",
        Height:"6'5ft",
        Wieght:"185lbs",
        Image:'',
    },
    {
        id: '15',
        Name:'Matt Ryan 4',
        Position:"Small Forward",
        Height:"6'7ft",
        Wieght:"215lbs",
        Image:'',
    },
];

module.exports = CelticsRoster